### ISSUE TITLE
TES3Merge error when running through MO2

### ISSUE THREAD

**Issue by Remiros64** [NullCascade/TES3Merge#26] opened 2021-12-28 04:05 UTC
First it says "WARNING: Issues were found with your Morrowind.ini file. See TES3Merge.log for details."
and after running it says: "A serious error has occurred. Please post the TES3Merge.log file to GitHub: https://github.com/NullCascade/TES3Merge/issues"

Here ill provide both my Morrowind.ini and TES3Merge.log

**Comment by Remiros64** [comment] 2021-12-28 04:08
Morrowind.ini from root: https://pastebin.com/TbUuyKZF
TES3Merge.log from root: https://pastebin.com/1YH23e50

**Comment by Remiros64** [comment] 2021-12-28 04:09
Please let me know if there is anything else I can provide to make the information clearer for an actionable diagnosis

**Comment by NullCascade** [comment] 2021-12-28 05:25
Give [this build](https://github.com/NullCascade/TES3Merge/files/7782970/tes3merge.zip) a try, let me know if you have any further issues.

**Comment by Remiros64** [comment] 2021-12-28 19:29
Sadly im getting an issue now where TES3Merge opens then instantly closes, Im guessing this might be a different problem? I just inserted this build where the last one was, at the root of my Morrowind

**Comment by NullCascade** [comment] 2021-12-29 01:08
What happens if you run it isolated in its own folder? It may be breaking with some other dlls.

**Comment by Remiros64** [comment] 2021-12-29 03:46
that build of TES3Merge isolated has the same behaviour when I run it through MO2 as did when I ran it through the root, It opens the black cmd prompt looking window for a split second, nothing in the overwrite for both cases

**Comment by Theokorra** [comment] 2021-12-29 03:57
I'm having the same issue. Had the error message that directed me here, tried the suggested build, now TES3Merge only opens for a second and then closes without updating the Merged Objects.esp.

**Comment by Remiros64** [comment] 2021-12-31 01:22
your problem might be different to mine, upload your TES3Merge.log and Morrowind.ini maybe it'll help NullCascade?

**Comment by Urraim** [comment] 2022-01-04 03:46
hi i have this issue too but interestingly eerything was working fine untill i added a few mods and suddenly i was getting this error, the log showed me it had the error after the npc 'fara' just like remiros 
, however iv since reverted back those mods and the issue persists after a different npc:

TES3Merge.log: https://github.com/NullCascade/TES3Merge/files/7805214/TES3Merge.log

sorry for making it a download this is my first post on this site

the only other thing i changed between tes3merge working correctly through mo2 and getting this error was that i updated wrye mash (https://www.nexusmods.com/morrowind/mods/45439?tab=description) to the beta version to get 1024 plugins since i had just started exceeding 255 plugins in my list :/ (i use wrye mash through mo2 just to mash lists)

hope this is helpful at all

i will try again with the mainwryemash version installed although i dont see how its related

**Comment by NullCascade** [comment] 2022-01-07 18:37
> I'm having the same issue. Had the error message that directed me here, tried the suggested build, now TES3Merge only opens for a second and then closes without updating the Merged Objects.esp.

> that build of TES3Merge isolated has the same behaviour when I run it through MO2 as did when I ran it through the root, It opens the black cmd prompt looking window for a split second, nothing in the overwrite for both cases

> I'm having the same issue. Had the error message that directed me here, tried the suggested build, now TES3Merge only opens for a second and then closes without updating the Merged Objects.esp.

Try [installing the .NET runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.1-windows-x64-installer).

**Comment by Remiros64** [comment] 2022-01-08 21:09
Hey Null! I did just that, now the prompt opens.. however I still get the same "A serious error has occurred." message, Here the log I get now:

[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/7834022/TES3Merge.log)

**Comment by Remiros64** [comment] 2022-01-08 22:35
> update: i was able to reproduce the error after borking my BCoM install a bit, i changed esp options for one of the BAIN patches without changing around the associated assets. so no issue on tes3merges side im my view ^^
> 
> repairing the mods that have red boxs in wrye mash can fix other instances of this error i believe.

ohhhh which BCoM options did you opt out of?! :o

**Comment by Urraim** [comment] 2022-01-09 02:17
@Remiros64: well it was caused by bad load order specifically i believe now, but in that instance it was changing from the addon 'improved inns expanded - expanded entertainers.esp'  to  'improved inns expanded.esp' but there i think i was wrong about the asset requirements change being the problem, since then i have consistenttly encountered the error when 'MainQuestOverhaul.esp' (the BCoM version) is too far down my load order, sorry i cannot be more specific i just move that esp to near the eginning and walla ! no errors, mlox can put it uneccssarily far down iv noticed, like if youre plugins are loaded automatically in alphabetical order, the ruleset for mlox wont then move it high enough so a manual load order is required unfortunatly
note im using mods which could possibly conflict and proabbly cause this : main quest enhancers and for a while i was using QTA but disabled it once i had gone through all of BCoMs optional esps one by one deactivating them untill i found that it was MQO 'causing' the error, i decided then to deactivate QTA since its rather ancient and i guessed it was the conflict and it fixed it for that instance of my load order, but the error still persisted in later load orders i made without QTA. i havnt tried without MQEnhancers yet. so basically i think the mlox error is caused by mod conflicts and can be resolved primarily with some simple load order shifting if you can identify the offending mod. 
it was main quest overhaul for me although i cant be sure what exacty it was conflicting with as i have 300 plugins active and i only maintain one modlist sorry :3
 if you have MainQuestOverhaul from BCoM try moving it up the list untill the merge works!

**Comment by NullCascade** [comment] 2022-01-09 02:29
> Hey Null! I did just that, now the prompt opens.. however, I still get the same "A serious error has occurred." message, Heres the log I get now:
> 
> [TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/7834022/TES3Merge.log)

Hey, progress. I thought I fixed that issue already though. Here's [a better build](https://github.com/NullCascade/TES3Merge/files/7834377/tes3merge.zip). It will still have the problem, but will tell you exactly what files it is having trouble digesting and dump their contents. Send that log to me and I can make a test case with the contained data to fix it.

**Comment by Remiros64** [comment] 2022-01-09 02:39
ughhhhhhh Null the new build kinda worked completely!!!!! (YEAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH THANK YOUUUUUU!!!!!)

Regardless! Heres the current log I have: [TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/7834382/TES3Merge.log)

**Comment by NullCascade** [comment] 2022-01-09 02:43
What the heck? That shouldn't have fixed anything. Unless it was actually fixed previously. Or you moved plugins around like Urraim suggested.

**Comment by Remiros64** [comment] 2022-01-09 02:47
@Urraim Damn that makes sense tbh I know that particular plugin of BCOM is very out of date because of how many times MQO was changing and from what I remember RP was waiting for that mod to die down a bit before he provided a newer patch for it but im just going to ask the BCOM discord channel but idk if this info changes anything... hmmmm

**Comment by Remiros64** [comment] 2022-01-09 02:50
hmm I removed some stuff with friends and foes (the mod and the westlys faces stuff that comes with it)! I'm going to add them back and see if I can still be alright but I was getting this error even after I removed F&F 7 days ago...

**Comment by Urraim** [comment] 2022-01-09 02:52
F&F merges fine i suspected that one too but it has yet to make a difference either way, i havnt begun an error by activating it nor has deactivating it ever fixed the error for me :p

**Comment by Remiros64** [comment] 2022-01-09 02:52
ehh... just tried re adding F&F and its associates and everything is still fine. A surprise but a welcome one!

**Comment by Urraim** [comment] 2022-01-09 03:01
ill try the build and see if MQO then merges when near the bottom of my list

**Comment by Remiros64** [comment] 2022-01-09 16:51
Not at all Urraim! Thank you for the input you're giving me a better idea of what went down than I ever could by myself lol

Now that the problem is fixed (so to speak) is it safe to close the issue?

**Comment by NullCascade** [comment] 2022-01-09 23:19
0.9, just released, should fix the last of the NPC and creature record merge issues.

If you find more, please open a new issue and I'll take a look.

**Closed by NullCascade** 2022-01-09 23:19 UTC
Labels: bug
